inherit_from: '.rubocop_todo.yml'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/AbcSize:
  Max: 18

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Max: 20
